### ISSUE TITLE
Spin up a dev server

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/api.distributed.press#10]
Context from email:

>1. hyperdrive-publisher sync. https://github.com/RangerMauve/hyperdrive-publisher/issues/8 Diego has a patch WIP. Mauve and I discussed to stand up a dev instance of Distributed Press and give SSH access to y’all so we can verify easily. (The “official” instance of Distributed Press at api.distributed.press is now serving the production COMPOST magazine and website of our cooperative, that’s why we are avoiding testing on that.) It’s on me to set up the instance.

So let's spin up a temporary server on Hypha's server, that is a parallel of `api.distributed.press` called `api.dev.distributed.press`. Everyone who wants to get SSH access can paste their pubkey here in this thread?

**Comment by martinheidegger** [comment]
Here is my pub 😉 

> ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8b3WA/mLduQrZqiLshFYbvDZGDtwPSduyxdS5CmBT+nYAZNbNgAu7iA+a1Qtd6EEiofNA9+cdtqfhEBYWG1Rb+pJZdceK/Fxt/e0kjbeEQwl/GGJmpRLS7qRa00O2kk2cNHOvxscVKr3DH3noN1XLOBmPQ8ZZ6amAa9lP31VYN55CFEUFJMPWw2a+7bp0yIi7bUgQjwt2PSse7fjuovUBUbheSAA8qjpYzSW2112XGgfgjM6QhrlajYZgZNVh+xAtDjC0BrvvcdEFB1FtzoQ0nVzNVzpgppgh09PyNcZ2bJGJyPFc64MlYP2qUW2WJyZt/ps5vgvZx50yutBgXtE/U52DbNTrumbbL13chyYyVBh2bXyRRvQF8Kr+sv+IHq/+YtuzWhneV72pvz1UL0ne7mMp3Iphyy18SkYYRdij96rYhIq7ye5lpsq5aFhMQYFeSce35Ov4G8Vl0PTNcn+5myaj4iaOiXGiQ+QcmEhZxlfvBxP/D06nXxK86KkzKXJ7gDjVPxJDggP4gdFPpSDkNhIza+hTT0gbPZjCxSDdaIZ+3dK94HF9we6Mbdyz0JwDcAR+7E/EGIr5wvCSSS04CCDFey/81FqHGShB36dG4p8Q5mNTxp49PFBLrpvH9rujhoXcYFTBVzYcmb5s/cz7eXXpnAOwP497q51PbQo/ww== martin.heidegger+dev@gmail.com

**Comment by benhylau** [comment]
@ASoTNetworks here's mine:
>ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC+mbERRuviaKzD1JOCY8q24+Bm40//jT0DvWh788Owd8Ke7QUubSOvX+vPV4n41X762ucJ3jKJcVPrsHvYq5Dq/O/aIf5O27D3kTmb5pt5UIOn+M+GGckp8/a8oAGkk1be8qwpTIuG7cPizrtkm7KokxZ7M4U4NFlS2bsTu2SQWh2QUigBlyeDlR+dN1rO//2h8uw8UkHTfdSs3Hy0xf7R9Umbyzs3oRlLn06NYdMF+X03tVfUhHwFZAFsV9IR1qGMG91gfEdY0k+f4pP553xplmvlPFm8j46vpIMv2fliYl9dhv9tRQaFdVIBMddxkMILqslMUXckLoDEZh98R4H+UBKaqrHmquOmQG5ZKnrQ35MliLuTJFhA++OY3xrGdpLMcZScDFI1UFrKzDKnwEV4Z+LFeoHqZtCnis+AN9+g39cI8IJd2SArrpL4N74gTWpPjDJc2kljOgYpviZsnEiDGQr3Ip1QP1hB9Lq346ydDG08QfnNVfkGigqk2VEex6E= benedict@benedict-home-2.home

**Comment by ASoTNetworks** [comment]
I have added both your public keys and you can login using `ssh sysadmin@srv1.dev.distributed.press`

**Comment by benhylau** [comment]
Thanks @ASoTNetworks.

@dpaez @rangermauve do you want access too? Once we have access set up I can walk you guys thru how this works, and reproduce the hypercore-publisher bugs I'm seeing.

**Comment by RangerMauve** [comment]
cc @martinheidegger

**Comment by RangerMauve** [comment]
Oh oops, I didn't realize he was already in the thread. :P I'm kinda busy with other stuff at the moment so I'll leave it to y'all to figure out unless you get stuck and need help somewhere. 💜

**Comment by luandro** [comment]
My [pub key here](https://github.com/luandro.keys)**.**

**Comment by ASoTNetworks** [comment]
@luandro thanks I have added your pub key.

**Comment by benhylau** [comment]
We should schedule a proper walk-through soon, maybe first week of May? For now you guys can do this to see where things are running:

```
~ ❯❯❯ ssh sysadmin@srv1.dev.distributed.press -i ~/.ssh/distributed-press-dev
sysadmin@srv1:~$ sudo su press
press@srv1:/home/sysadmin$ cd ~

press@srv1:~$ ls -la
total 44
drwxr-xr-x 7 press users 4096 Apr 15 11:37 .
drwxr-xr-x 4 root  root  4096 Mar 26 23:48 ..
drwxr-xr-x 6 press users 4096 Mar 27 00:01 api.distributed.press
-rw------- 1 press users   27 Apr 15 11:37 .bash_history
-rw-r--r-- 1 press users  220 Apr 18  2019 .bash_logout
-rw-r--r-- 1 press users 3526 Apr 18  2019 .bashrc
drwx-----x 3 press users 4096 Mar 27 00:01 .distributed-press
drwxr-xr-x 5 press users 4096 Apr  9 00:06 .ipfs
drwxr-xr-x 3 press users 4096 Mar 26 23:59 .local
drwxr-xr-x 3 press users 4096 Mar 27 00:01 .npm
-rw-r--r-- 1 press users  807 Apr 18  2019 .profile

press@srv1:~$ ls -l api.distributed.press
total 100
drwxr-xr-x 3 press users  4096 Mar 27 00:01 api
drwxr-xr-x 3 press users  4096 Mar 27 00:01 backend
-rw-r--r-- 1 press users 34523 Mar 27 00:01 LICENSE
-rw-r--r-- 1 press users 31875 Mar 27 00:01 logo-distributedpress.png
-rw-r--r-- 1 press users   311 Mar 27 00:01 package-lock.json
drwxr-xr-x 3 press users  4096 Mar 27 00:01 pinning-services
-rw-r--r-- 1 press users 14953 Mar 27 00:01 README.md

press@srv1:~$ systemctl status distributed-* ipfs dat-store
● ipfs.service - IPFS daemon
   Loaded: loaded (/etc/systemd/system/ipfs.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-09 00:06:16 EDT; 6 days ago
 Main PID: 686 (ipfs)
    Tasks: 17 (limit: 2375)
   Memory: 910.1M
   CGroup: /system.slice/ipfs.service
           └─686 /usr/local/bin/ipfs daemon --enable-namesys-pubsub

● dat-store.service - Dat storage provider, keeps dats alive in the background.
   Loaded: loaded (/etc/systemd/system/dat-store.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-09 00:06:16 EDT; 6 days ago
 Main PID: 695 (node)
    Tasks: 11 (limit: 2375)
   Memory: 41.7M
   CGroup: /system.slice/dat-store.service
           └─695 node /usr/bin/dat-store run-service --port 3472 --authorization-username press --authorization-password 255e6cf4f0fd80eb25d7d4cc5b13c72b931afd18000d328206e5e755c10d47d3

● distributed-pinning.service - Distributed Pinning Service.
   Loaded: loaded (/etc/systemd/system/distributed-pinning.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-09 00:06:16 EDT; 6 days ago
 Main PID: 687 (node)
    Tasks: 7 (limit: 2375)
   Memory: 45.1M
   CGroup: /system.slice/distributed-pinning.service
           └─687 /usr/bin/node index.js

● distributed-api.service - Distributed API Service.
   Loaded: loaded (/etc/systemd/system/distributed-api.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-09 00:06:16 EDT; 6 days ago
 Main PID: 682 (node)
    Tasks: 7 (limit: 2375)
   Memory: 30.7M
   CGroup: /system.slice/distributed-api.service
           └─682 /usr/bin/node index.js

● distributed-backend.service - Distributed Backend Service.
   Loaded: loaded (/etc/systemd/system/distributed-backend.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2021-04-09 00:06:16 EDT; 6 days ago
 Main PID: 690 (node)
    Tasks: 7 (limit: 2375)
   Memory: 23.3M
   CGroup: /system.slice/distributed-backend.service
           └─690 /usr/bin/node index.js
```

**Comment by fauno** [comment]
`ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKoo+wGcHAsTfX9fiF46iO8g9nmiRSw53rD6xVtOyDE0`

**Comment by benhylau** [comment]
We have this now
