### ISSUE TITLE
Corrupt dat-store

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/api.distributed.press#19]
Found that dat-store got corrupt after several months, even though we are only pinning several text files of API responses every 15 min. To recover, we had to:

1. Wipe `~/.local/share/dat-store-nodejs`
2. Delete all `~/.distributed-press/data/projects/*/private/dat-seed-*`

This is related to existing hypercore problems using our current stack.

After performing the above, [this link](https://hyper.distributed.press/api.staging.compost.digital/v0/monetization/balances.json) works again.

**Comment by RangerMauve** [comment]
No longer relevant in v1
