### ISSUE TITLE
Test video publish and playback

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/api.distributed.press#21]
🎟️ **Re-ticketed from:** #  
📅 **Due date:** Feb 13, 2021  
🎯 **Success criteria:** Make sure we can publish large video and play back.  

## Task Summary

Test 500 MB video file upload via `publish` API in Distributed Press. Test playback on different browser, or do we need to embed a video.js.

Test video link in chat.

## To Do

- [ ] Test publishing
- [ ] Check WWW, IPFS, Hypercore
- [ ] Check playback on desktop and mobile browsers

**Comment by jackyzha0** [comment]
Closing (relevant to v0)
