### ISSUE TITLE
Fix publishing with hyperdrive-publisher

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/api.distributed.press#22]
🎟️ **Re-ticketed from:** https://github.com/hyphacoop/distributed-press-organizing/issues/7#issuecomment-751606757  
📅 **Due date:** N/A  
🎯 **Success criteria:** Publish Hypercore content completely and reliably.  

## Task Summary

Hypercore publishing is currently incomplete and unreliable, due to a [known bug in hyperdrive-publisher](https://github.com/RangerMauve/hyperdrive-publisher/issues/8).

## To Do

- [ ] Fix https://github.com/RangerMauve/hyperdrive-publisher/issues/8
- [ ] Update code on Distributed Press

**Comment by jackyzha0** [comment]
Closing (relevant to v0)
