### ISSUE TITLE
Test publishing of fil.org website

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/api.distributed.press#25]
The fil.org website has their code [here](https://github.com/FilecoinFoundationWeb/filecoin-foundation-site) we can try to publish the static site with Distributed Press. Instructions from their dev:

1. Clone the repo and make sure you have Node installed locally (tested on Node v14, v16 seems a little unstable still)
2. Build with `npm ci && npm run generate`
3. This creates a /dist directory in the site root, which can be tarballed for your purposes

(You can also just run it as a served resource from Node on localhost with npm ci && npm run dev, but I imagine you just want the static version)

**Comment by YurkoWasHere** [comment]
Skipped creation of API KEY as its internal

```
git clone https://github.com/FilecoinFoundationWeb/filecoin-foundation-site.git
cd filecoin-foundation-site
npm ci 
npm run generate

PROJECT_API_KEY="<<REDACTED>>"
echo "{"domain": "filecoinfoundationweb.hypha.coop"}" > config.json

# configure site
 curl -v https://api.distributed.press/v0/publication/configure \
    -H "Content-Type: multipart/form-data" \
    -H "Accept: application/json" \
    -H "Authorization: Bearer ${PROJECT_API_KEY}" \
    -F "file=@config.json"

# Tar and Upload Site
tar -czhv -f www.tar.gz -C dist .
curl -v https://api.distributed.press/v0/publication/publish \
    -H "Content-Type: multipart/form-data" \
    -H "Accept: application/json" \
    -H "Authorization: Bearer ${PROJECT_API_KEY}" \
    -F "file=@www.tar.gz"
```

**Comment by benhylau** [comment]
The site is published to:
https://ipfs.distributed.press/ipns/filecoinfoundationweb.hypha.coop/

Links fail the same as the official:
https://ipfs.distributed.press/ipns/fil.org/

The site itself is not DWeb compatible bc of absolute links.

**Comment by jackyzha0** [comment]
Closing (relevant to v0)
