### ISSUE TITLE
Integration with Sutty: DNS and DNSLinks

### ISSUE THREAD

**Issue by fauno** [hyphacoop/api.distributed.press#26]
Hi! I'm opening this in a two part proposal.

Right now, Distributed Press requires domains to be delegated and managed by it, so it can keep DNSLinks and other records updated.  In Sutty we have a mixed bag for DNS management and in many cases it won't be possible to delegate them to Distributed Press.  I need to write about our DNS in more detail, but basically each Sutty node is its own nameserver.  If a node is down, its information goes down with it, so we don't have to make changes to other nodes.

So, if Distributed Press could act as a DNS authoritative server for the `_dnslink` zone of each of the domains it hosts:

* Authoritative name servers (Sutty's or otherwise) for an `example.org` domain would publish `_dnslink NS nsX.distributed.press` records, where X is the nameserver number.  This delegates control of `_dnslink` subdomain to Distributed Press, so it doesn't need full control of the DNS zone, only the `_dnslink` subdomain.

* The Distributed Press backend would become a DNS server serving `_dnslink TXT dnslink=...` records.  These could be generated on the fly via a key-value map of domain to latest CID.

* TTLs could be kept low, ie. 60 seconds.

* Adding support for AXFR/IXFR to the backend would allow to keep any number of nsX.distributed.press nameservers.  Even the Distributed Press API could be served privately, and more stablished DNS nameservers (like [knot](knot-dns.cz/) or [nsd](https://www.nlnetlabs.nl/projects/nsd/about/)) could become public replicators, with rate limits and other security features.

> This not only makes DNSLink lookup more efficient by only returning relevant TXT records but enables you to improve the security of an automated setup or **delegate control over your DNSLink records to a third party without giving away complete control over the original DNS zone**. [source](https://docs.ipfs.io/concepts/dnslink/#:~:text=This%20not%20only%20makes%20DNSLink%20lookup%20more%20efficient%20by%20only%20returning%20relevant%20TXT%20records%20but%20enables%20you%20to%20improve%20the%20security%20of%20an%20automated%20setup%20or%20delegate%20control%20over%20your%20DNSLink%20records%20to%20a%20third%20party%20without%20giving%20away%20complete%20control%20over%20the%20original%20DNS%20zone.) (June, 2022)

## Questions

* How would it play with other protocols?  I tried to find documentation on Hypercore but couldn't find anything, how does hyper://example.org work?

**Comment by RangerMauve** [comment]
One thing I was thinking would be useful to revisit is using IPNS public keys instead of just DNS link for resolution.

If we did that we could instead generate a IPNS key, and then get sutty or whatever DNS operator to update their DNS records just once to point to `/ipns/keyhere`. From there DP could update the IPNS key however it wants and updates could propogate via IPNS pubsub almost instantly.

**Comment by RangerMauve** [comment]
I'm also hoping to get similar things working for DNSLink in Hyper and BitTorrent.

We could have the DNSLink point to mutable public key based things, and skip having to touch the DNS APIs unless absolutely necessary.

**Comment by fauno** [comment]
Hi! Here's a [mockup implementation for DNSLink delegated to Distributed Press](https://0xacab.org/sutty/distributed-press-ns) :D  It doesn't do much just show what we meant with the proposal.

This way there's no need for provider-specific implementations, Distributed Press manages its own records.

It could be run behind a [DNS proxy](https://www.knot-dns.cz/docs/3.2/html/modules.html#dnsproxy-tiny-dns-proxy) for safety.

**Comment by RangerMauve** [comment]
Getting a 404, should I mace an 0xacab account to make some stuff smoother?

**Comment by RangerMauve** [comment]
One thing I'm not sure about is whether we should use DNS services and add records there (can we even if it's for domains we don't own?), or should we be creating a DNS server that we control programmatically?

**Comment by fauno** [comment]
Sorry, I forgot to make it a public repo!  You can review it now.

The idea is that we can delegate control over _dnslink.any.doma.in to Distributed Press to handle those records and keep any.doma.in in their own DNS servers.  Currently APIv0 requires full delegation to Distributed Press.

For instance, we have this in place for our servers:

```bash
drill ns sutty.nl
# currently delegated to njal.la 
# sutty.nl.       21600   IN      NS      2-can.njalla.in.
# sutty.nl.       21600   IN      NS      3-get.njalla.fo.
# sutty.nl.       21600   IN      NS      1-you.njalla.no.

drill ns athshe.sutty.nl
# every server is auto-delegated
# athshe.sutty.nl.        3600    IN      NS      athshe.sutty.nl.

drill ns anarres.sutty.nl
# anarres.sutty.nl.       3600    IN      NS      anarres.sutty.nl.

```

In this proposal

```bash
drill ns _dnslink.sutty.nl
# could reply with nsX.distributed.press
# _dnslink.sutty.nl.       3600    IN      NS      ns1.distributed.press.
# _dnslink.sutty.nl.       3600    IN      NS      ns2.distributed.press.
# _dnslink.sutty.nl.       3600    IN      NS      ns3.distributed.press.
```

And Distributed Press doesn't need to implement an API specific to any DNS provider (or a library that does this), it's just DNS.

**Comment by fauno** [comment]
Checked with some registrar/nameservers, because apparently I've registered domains everywhere:

| Provider | Type | NS records for subdomains |
| - | - | - |
| Njalla | Both | Yes |
| Hurricane Electric | Nameserver | Yes |
| Cloudflare | Everything | Yes |
| GoDaddy | Both | ??? |
| Free DNS | Nameserver | Yes |
| Freenom | Both | ??? |
| Name | Both | Yes |

**Comment by fauno** [comment]
Issuing Let's Encrypt certificates should be deprecated on APIv1

**Comment by YurkoWasHere** [comment]
Siteground does NOT support NS at all (wasted hours with support and gave up)
CPANEL - user cannot make the change, has to be server admin
Hurricane Electric (he.dns.net) - full support

**Comment by fauno** [comment]
@RangerMauve maybe support a site-specific record as a fallback?  I'm not clear if ALIAS or CNAME can point to TXT records, but something like this:

```zonefile
; Regular records
@ IN A 0.0.0.0
; Delegate to DP
_dnslink IN NS ns.distributed.press.
; Fallback to CNAME if NS is not supported
_dnslink IN CNAME example-com.distributed.press.
; Could also be site ID but nanoid is case-sensitive
```

**Comment by RangerMauve** [comment]
We'll need to figure out if the dns-query library supports CNAME/ALIAS

Here's where I use it to look up a TXT record: https://github.com/RangerMauve/hyper-sdk/blob/master/index.js#L101

I don't see any references to CNAME or ALIAS, so it might be up to individual DNS over HTTPS resolvers. 🤔

**Comment by fauno** [comment]
I think we can start with NS as planned and figure out fallbacks when a
nameserver doesn't support delegation.

**Comment by jackyzha0** [comment]
@fauno is this closed by #41 ?

**Comment by RangerMauve** [comment]
Let's close after we add some unit tests and do some manual testing.

**Comment by RangerMauve** [comment]
Did some manual testing on `example2.mauve.moe` today and it all seems to be working! Setting up an NS record pointing to `api.distributed.press` for `_dnslink.example2.mauve.moe` worked like a charm. :)  This was with namecheap in my case.

Tomorrow I'll try to test out sutty's connection to the staging version of DP to see how it goes. I'm feeling pretty confident it'll just work.

**Comment by jackyzha0** [comment]
Closing as completed :)
