### ISSUE TITLE
Don't run public gateway

### ISSUE THREAD

**Issue by makew0rld** [hyphacoop/api.distributed.press#28]
Set [`Gateway.NoFetch`](https://github.com/ipfs/kubo/blob/master/docs/config.md#gatewaynofetch) to true.

> When set to true, the gateway will only serve content already in the local repo and will not fetch files from the network.

This prevents the IPFS gateway from being abused as a public general gateway.

**Comment by fauno** [comment]
We're thinking of doing this in Sutty too, but it seems you need to add all domain names to a JSON array and reload the config?  I haven't checked if it can be done through IPFS API

**Comment by makeworld-the-better-one** [comment]
My understanding is that you don't need to set any domain names for this to work, it's an entirely separate config setting. You just need to set `Gateway.NoFetch` and it'll work.

**Comment by jackyzha0** [comment]
Closing (applies to v0)
