### ISSUE TITLE
Cronjob shouldn't have output

### ISSUE THREAD

**Issue by fauno** [hyphacoop/api.distributed.press#29]
The staging server logs are full of emails sent to root (plus postfix complaining about the hostname).  Inspecting /var/mail/root is full of "All done" emails from cron.

Not sure if this is going to be kept for APIv1 but it could just `exit 0` and be verbose only on errors, so you don't have as many useless emails, or run it with `chronic` which ignores output if everything goes well.

**Comment by fauno** [comment]
I made a mistake filtering emails and I emptied the mailbox, there were 2488 :B

**Comment by RangerMauve** [comment]
No longer relevant as of v1
