### ISSUE TITLE
Holepunch url not human readable

### ISSUE THREAD

**Issue by sutty-coop** [hyphacoop/api.distributed.press#52]
![Screenshot_20230424_175701](https://user-images.githubusercontent.com/113475467/234116203-67755362-6733-41cd-8e53-995985db7803.png)

The hyper url is informed by the api.

Here's the urls in question:
https://mi-blogcito-personal.sutty.nl/
hyper://1rtaxkd447w8db3poxt8nohjt7k5honzys694p34wm8cxa7d7rso/

**Comment by jackyzha0** [comment]
It should be using `hyper.gateway` which is `https://mi--blogcito--personal-sutty-nl.hyper.hypha.coop/`

**Comment by RangerMauve** [comment]
Good catch. We're currently setting the hyper link to the raw key instead of using DNS

https://github.com/hyphacoop/api.distributed.press/blob/main/protocols/hyper.ts#L61

This should instead be

```javascript
link = `hyper://${subdomain}`
```
