### ISSUE TITLE
Bump Pinned Version in Ansible Script

### ISSUE THREAD

**Issue by errbufferoverfl** [hyphacoop/api.distributed.press#61]
Hey folks!

I recently deployed my own instance of `distributed.press` and found that because the version of distributed press is pinned to `v1.0.0` in [Ansible](https://github.com/hyphacoop/api.distributed.press/blob/b23534e6652cab20c2b10a3dcd85529344139462/ansible/roles/distributed_press/defaults/main.yml#L17), hypercore doesn't work out of the box, instead serving a blank index page! 😅

I wasn't sure if there was a reason for this so haven't opened a PR but more than happy too.

**Comment by jackyzha0** [comment]
Good catch! I think patch incoming in this diff: https://github.com/hyphacoop/api.distributed.press/pull/59/files#diff-0783fa9333b6c9bf277a8f32e6ab3eb6d82d88a6c0539eea24200d353e3bc2dcL17

Hopefully landing soon :) Closing as we are aware of this and will ship a fix in the next minor/patch
