### ISSUE TITLE
feature: node.js repository with default github actions and full-stack react starter SDK

### ISSUE THREAD

**Issue by akhileshthite** [hyphacoop/api.distributed.press#72]
Create a node.js repository featuring all the default GitHub Actions, enabling users to fork / use the "Use this template" option on GitHub. Maybe, also consider creating a full-stack starter React SDK;`npx create-dp-app`.

We could create separate repositories for these purposes or add a directory named `packages` in this repository.

**Comment by RangerMauve** [comment]
I think a template repo would be great, maybe the cli tool could wait until after we see if the template repo is useful?

**Comment by akhileshthite** [comment]
> I think a template repo would be great, maybe the cli tool could wait until after we see if the template repo is useful?

Yeah, works.

**Comment by akhileshthite** [comment]
https://github.com/hyphacoop/staticpub.distributed.press
https://github.com/hyphacoop/distributed-press-cli
