### ISSUE TITLE
Support X-Ipfs-Path headers for static hosting

### ISSUE THREAD

**Issue by fauno** [hyphacoop/api.distributed.press#73]
> IPFS Companion can redirect traditional HTTP requests to IPFS if the x-ipfs-path response header is provided.
> 
> Additionally, some browser vendors like Brave may display an Open using IPFS button on the address bar when this header is returned for the root document in the current tab.
>
> [source](https://docs.ipfs.tech/how-to/companion-x-ipfs-path-header/#overview)

I think this can be done statically on Nginx config with something like this:

```nginx
server {
  add_header "X-Ipfs-Path" "/ipns/$ssl_server_name";
}
```

**Comment by RangerMauve** [comment]
If you want you could try doing a PR here: https://github.com/hyphacoop/api.distributed.press/blob/main/ansible/roles/distributed_press/templates/nginx-static.j2

**Comment by fauno** [comment]
Too bad we can't use a meta http-equiv tag: https://github.com/ipfs/ipfs-companion/issues/1013
